export type Screen =
  | 'splash'
  | 'login'
  | 'forgot-password'
  | 'change-password'
  | 'home'
  | 'tracking'
  | 'notifications'
  | 'history'
  | 'profile'
  | 'select-stop'
  | 'driver-home'
  | 'driver-route'
  | 'driver-pickup'
  | 'driver-incident'
  | 'driver-notifications'
  | 'driver-profile';